"""add_book_speaker_assignments_table

Revision ID: 823f1774abe4
Revises: f46890a1eaf9
Create Date: 2025-11-18 10:50:44.803131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '823f1774abe4'
down_revision: Union[str, None] = 'f46890a1eaf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_speaker_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_speaker_assignments_id'), 'book_speaker_assignments', ['id'], unique=False)
    # Добавляем уникальный индекс для предотвращения дублирования назначений
    op.create_index('ix_book_speaker_unique', 'book_speaker_assignments', ['book_id', 'speaker_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_book_speaker_unique', table_name='book_speaker_assignments')
    op.drop_index(op.f('ix_book_speaker_assignments_id'), table_name='book_speaker_assignments')
    op.drop_table('book_speaker_assignments')
    # ### end Alembic commands ###



