"""remove email from users

Revision ID: c47bb91a04f6
Revises: bde41c1e6054
Create Date: 2025-11-17 14:59:44.340741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47bb91a04f6'
down_revision: Union[str, None] = 'bde41c1e6054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###

